FROM registry.access.redhat.com/ubi9/ubi-init:latest as builder

RUN dnf install -y gcc make git && rm -rf /var/lib/apt/lists/*

ENV GOLANG_VERSION 1.19.8
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 e1a0bf0ab18c8218805a1003fd702a41e2e807710b770e787e5979d1cf947aba

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf golang.tar.gz \
    && rm golang.tar.gz

ENV PATH /usr/local/go/bin:$PATH

RUN mkdir -p /go/build && chmod -R 0755 /go

WORKDIR /go/src/github.com/coreos/etcd

ENV goos linux
ENV GOARCH amd64
ENV GO111MODULE on

COPY . .

RUN make

FROM registry.access.redhat.com/ubi9/ubi-minimal as redhat-production

RUN microdnf update -y \
    && microdnf install -y shadow-utils \
    && adduser --no-create-home --user-group nbycomp \
    && microdnf remove -y shadow-utils

USER nbycomp

WORKDIR /var/lib/etcd/

EXPOSE 2379 2380

COPY --from=builder /go/src/github.com/coreos/etcd/bin/etcd /usr/local/bin/
COPY --from=builder /go/src/github.com/coreos/etcd/bin/etcdctl /usr/local/bin/

COPY LICENSE /licenses/

CMD ["/usr/local/bin/etcd"]
